import { NextRequest, NextResponse } from 'next/server'

/**
 * Server-side PDF export endpoint
 * Returns an HTML document that can be printed/saved as PDF
 *
 * For production enhancement, install pdfkit:
 * npm install pdfkit
 * Then use pdfkit library for better PDF generation
 */

export async function POST(request: NextRequest) {
  try {
    const { title, content, tone } = await request.json()

    if (!title || !content) {
      return NextResponse.json(
        { error: 'Title and content are required' },
        { status: 400 }
      )
    }

    // Generate HTML that can be saved as PDF
    const htmlContent = generateHTMLForPDF(title, content, tone)

    // Return as downloadable HTML (can be printed to PDF)
    return new NextResponse(htmlContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `attachment; filename="${sanitizeFilename(title)}.html"`,
      },
    })
  } catch (error: any) {
    console.error('PDF export error:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to export PDF' },
      { status: 500 }
    )
  }
}

function generateHTMLForPDF(title: string, content: string, tone: string): string {
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)} - Cover Letter</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      background: #fff;
      padding: 40px 20px;
    }

    .container {
      max-width: 8.5in;
      height: 11in;
      margin: 0 auto;
      padding: 1in;
      background: white;
      box-shadow: 0 0 20px rgba(0,0,0,0.1);
    }

    .header {
      border-bottom: 2px solid #0066cc;
      padding-bottom: 15px;
      margin-bottom: 25px;
    }

    .title {
      font-size: 18px;
      font-weight: 700;
      color: #0066cc;
      margin-bottom: 5px;
    }

    .meta {
      display: flex;
      justify-content: space-between;
      font-size: 11px;
      color: #666;
    }

    .tone-badge {
      display: inline-block;
      background: #e6f2ff;
      color: #0066cc;
      padding: 2px 8px;
      border-radius: 3px;
      font-weight: 600;
      font-size: 10px;
    }

    .content {
      font-size: 11px;
      line-height: 1.8;
      white-space: pre-wrap;
      word-wrap: break-word;
      margin-bottom: 30px;
      min-height: 400px;
    }

    .content p {
      margin-bottom: 10px;
    }

    .footer {
      border-top: 1px solid #ddd;
      padding-top: 10px;
      margin-top: 30px;
      font-size: 9px;
      color: #999;
      text-align: center;
    }

    @media print {
      body {
        padding: 0;
        background: white;
      }
      .container {
        max-width: 100%;
        height: auto;
        box-shadow: none;
        padding: 0.5in;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="title">${escapeHtml(title)}</div>
      <div class="meta">
        <div>
          <span class="tone-badge">${escapeHtml(tone.toUpperCase())}</span>
        </div>
        <div>${today}</div>
      </div>
    </div>

    <div class="content">
${escapeHtml(content).split('\n').map(line => `      ${line}`).join('\n')}
    </div>

    <div class="footer">
      <p>Generated by ApplyMaster.ai • Cover Letter</p>
    </div>
  </div>

  <script>
    // Auto-print dialog on load (optional)
    // Uncomment the line below to automatically show print dialog
    // window.print();
  </script>
</body>
</html>`
}

function escapeHtml(text: string): string {
  const map: { [key: string]: string } = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  }
  return text.replace(/[&<>"']/g, m => map[m])
}

function sanitizeFilename(filename: string): string {
  return filename
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50) || 'cover-letter'
}
