import { NextRequest } from 'next/server'
import { createClient } from '@/lib/supabase-server'
import { htmlToPdf, escapeHtml, safeFilename, pdfResponse } from '@/lib/pdf'

export const maxDuration = 60

/**
 * Cover letter as a real PDF.
 *
 * This used to return an HTML page, which the editor then saved with a .pdf
 * extension — so every exported "PDF" was a web page that PDF readers
 * refuse to open. The page also carried a tone badge ("PROFESSIONAL") and a
 * "Generated by ApplyMaster.ai" footer: marks nobody should send to an
 * employer.
 *
 * Now: a plain business letter — the sender's name and contact details,
 * the date, and the body — printed to PDF.
 */

type Sender = { name: string | null; email: string | null; phone: string | null; location: string | null; linkedin: string | null }

async function senderFor(userId: string, email: string | null): Promise<Sender> {
  const supabase = createClient()
  const [{ data: profile }, { data: parsed }] = await Promise.all([
    supabase.from('profiles').select('full_name').eq('id', userId).maybeSingle(),
    supabase.from('parsed_resumes').select('*').eq('user_id', userId).order('created_at', { ascending: false }).limit(1).maybeSingle(),
  ])
  const p = (parsed ?? {}) as Record<string, unknown>
  const str = (v: unknown) => (typeof v === 'string' && v.trim() ? v.trim() : null)
  return {
    name: str(profile?.full_name) ?? str(p.full_name),
    email: str(p.email) ?? email,
    phone: str(p.phone),
    location: str(p.location),
    linkedin: str(p.linkedin_url),
  }
}

function letterHtml(body: string, s: Sender): string {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const contact = [s.email, s.phone, s.location, s.linkedin].filter(Boolean).map(v => escapeHtml(v!)).join(' &nbsp;·&nbsp; ')

  // Blank lines separate paragraphs; single newlines inside one (a
  // signature block, say) are kept as line breaks.
  const paragraphs = body
    .replace(/\r\n/g, '\n')
    .split(/\n{2,}/)
    .map(p => p.trim())
    .filter(Boolean)
    .map(p => `<p>${escapeHtml(p).replace(/\n/g, '<br>')}</p>`)
    .join('\n')

  return `<!doctype html><html><head><meta charset="utf-8"><style>
  @page { size: A4; margin: 22mm 22mm 20mm; }
  body { font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; color: #16181d; font-size: 11pt; line-height: 1.55; margin: 0; }
  .name { font-size: 17pt; font-weight: 700; margin: 0; }
  .contact { font-size: 9pt; color: #4a5160; margin: 3px 0 0; }
  .rule { border: 0; border-top: 1px solid #cdd6e2; margin: 14px 0 18px; }
  .date { color: #4a5160; margin: 0 0 18px; }
  p { margin: 0 0 11px; }
</style></head><body>
  ${s.name ? `<p class="name">${escapeHtml(s.name)}</p>` : ''}
  ${contact ? `<p class="contact">${contact}</p>` : ''}
  ${s.name || contact ? '<hr class="rule">' : ''}
  <p class="date">${today}</p>
  ${paragraphs}
</body></html>`
}

export async function POST(request: NextRequest) {
  const supabase = createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return Response.json({ error: 'Sign in to export' }, { status: 401 })

  try {
    const { title, content } = await request.json()
    if (!content || typeof content !== 'string' || !content.trim()) {
      return Response.json({ error: 'The letter is empty' }, { status: 400 })
    }

    const pdf = await htmlToPdf(letterHtml(content, await senderFor(user.id, user.email ?? null)))
    return pdfResponse(pdf, safeFilename(title, 'cover-letter'))
  } catch (err) {
    console.error('cover letter export error:', err)
    return Response.json({ error: 'Could not build the PDF' }, { status: 500 })
  }
}
